export const enum AppErrorTypeEnum {
    DB_NO_ENTRIES,
    DB_ENTITY_EXISTS,
    DB_ENTITY_NOT_FOUND,
    DB_CANNOT_UPDATE,
    DB_NOTHING_TO_UPDATE,
    DB_CANNOT_CREATE,
    INVALID_CREDENTIALS_EXCEPTION,
    DB_INVALID_OBJECT_ID,
    CANNOT_UPLOAD_IMAGE,
    DB_INVALID_RANGE
}
